In [2]:
# ****************************************************************
#                             PANDAS
# ****************************************************************

In [3]:
# Pandas = Data Analysis Library in Python

# It is used for:

# Working with tables (like Excel)
# Data cleaning
# Data analysis
# Handling missing values
# Filtering data

In [4]:
# Why Pandas?

# You have data like:

# Name	Salary	Experience
# A	25000	1
# B	40000	3

# In NumPy → only numbers, no column names 
# In Pandas → structured table with names

In [5]:
import pandas as pd

In [6]:
#1D data
salary = pd.Series([25000, 40000, 60000])
print(salary)

0    25000
1    40000
2    60000
dtype: int64

In [7]:
# With Custom Index
salary = pd.Series([25000,40000,60000], index=["A","B","C"])
print(salary)

A    25000
B    40000
C    60000
dtype: int64

In [25]:
# DataFrame (very important)

# Method : From Dictionary
data = {
    "Name": ["A", "B", "C"],
    "Salary": [25000, 40000, 60000],
    "Experience": [1, 3, 5]
}

df = pd.DataFrame(data)

df

  Name  Salary  Experience
0    A   25000           1
1    B   40000           3
2    C   60000           5

In [9]:
# Basic Info
print(df.shape)   # rows, columns
print(df.columns) # column names
print(df.dtypes)  # data types

(3, 3)
Index(['Name', 'Salary', 'Experience'], dtype='object')
Name          object
Salary         int64
Experience     int64
dtype: object

In [24]:
# Access Column
df["Salary"]

0    25000
1    40000
2    60000
Name: Salary, dtype: int64

In [23]:
# Add New Column
df["Bonus"] = [2000, 3000, 5000]
df

   Salary  Experience  Bonus    PF
0   25000           1   2000  1500
1   40000           3   3000  1500
2   60000           5   5000  1500

In [12]:
#Deleting column
df = df.drop("Name", axis = 1)

In [22]:
df

   Salary  Experience  Bonus    PF
0   25000           1   2000  1500
1   40000           3   3000  1500
2   60000           5   5000  1500

In [21]:
#Adding constant column
df["PF"] = 1500
df

   Salary  Experience  Bonus    PF
0   25000           1   2000  1500
1   40000           3   3000  1500
2   60000           5   5000  1500

In [20]:
df.head(2)

   Salary  Experience  Bonus    PF
0   25000           1   2000  1500
1   40000           3   3000  1500

In [19]:
df.tail(2)

   Salary  Experience  Bonus    PF
1   40000           3   3000  1500
2   60000           5   5000  1500

In [17]:
df.describe()

             Salary  Experience        Bonus      PF
count      3.000000         3.0     3.000000     3.0
mean   41666.666667         3.0  3333.333333  1500.0
std    17559.422921         2.0  1527.525232     0.0
min    25000.000000         1.0  2000.000000  1500.0
25%    32500.000000         2.0  2500.000000  1500.0
50%    40000.000000         3.0  3000.000000  1500.0
75%    50000.000000         4.0  4000.000000  1500.0
max    60000.000000         5.0  5000.000000  1500.0