In [3]:
# *************************************************************************************************************************
#                                          DATA CLEANING WITH PANDAS 
# *************************************************************************************************************************

In [4]:
data = {
    "Customer_ID": ["C1", "C2", "C3", "C4", "C5", "C5"],
    "Signup_Date": [
        "2022-01-01",
        "2022-02-15",
        "2022-03-10",
        "2022-01-01",
        "2022-05-20",
        "2022-05-20"
    ],
    "Gender": ["Male", "Female", "male", "FEMALE", "Male", None],
    "Age": [25, 30, None, 45, 28, 28],
    "Annual_Income": [50000, None, 60000, 45000, None, None],
    "City": ["Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Delhi"]
}

In [7]:
import pandas as pd
df = pd.DataFrame(data)
df

  Customer_ID Signup_Date  Gender   Age  Annual_Income     City
0          C1  2022-01-01    Male  25.0        50000.0   Mumbai
1          C2  2022-02-15  Female  30.0            NaN    Delhi
2          C3  2022-03-10    male   NaN        60000.0  Chennai
3          C4  2022-01-01  FEMALE  45.0        45000.0   Mumbai
4          C5  2022-05-20    Male  28.0            NaN    Delhi
5          C5  2022-05-20    None  28.0            NaN    Delhi

In [ ]:
# --------------------------------
# Step-by-Step Data Cleaning
# --------------------------------

In [ ]:
# -----------------------
# # 1. Understand Data
# -----------------------

In [9]:
df.shape

(6, 6)

In [19]:
df.head()

  Customer_ID Signup_Date  Gender   Age  Annual_Income     City
0          C1  2022-01-01    Male  25.0        50000.0   Mumbai
1          C2  2022-02-15  Female  30.0            NaN    Delhi
2          C3  2022-03-10    male   NaN        60000.0  Chennai
3          C4  2022-01-01  FEMALE  45.0        45000.0   Mumbai
4          C5  2022-05-20    Male  28.0            NaN    Delhi

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    6 non-null      object
 1   Signup_Date    6 non-null      object
 2   Gender         5 non-null      object
 3   Age            5 non-null      float64
 4   Annual_Income  3 non-null      float64
 5   City           6 non-null      object
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes

In [12]:
df.columns

Index(['Customer_ID', 'Signup_Date', 'Gender', 'Age', 'Annual_Income', 'City'], dtype='object')

In [ ]:
#------------------------------
# 2. Handle Missing Values
#------------------------------

In [15]:
# Check missing
df.isna().sum()

Customer_ID      0
Signup_Date      0
Gender           1
Age              1
Annual_Income    3
City             0
dtype: int64

In [17]:
df.isnull().sum()

Customer_ID      0
Signup_Date      0
Gender           1
Age              1
Annual_Income    3
City             0
dtype: int64

In [ ]:
# Columns with issues:
# Age → missing
# Annual_Income → missing
# Gender → missing

In [32]:
# Fix Age (Numerical → Mean)

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Age"]
df["Age"].isnull().sum()

np.int64(0)

In [33]:
df["Annual_Income"] = df["Annual_Income"].fillna(df["Annual_Income"].mean())

In [34]:
df["Annual_Income"]

0    50000.000000
1    51666.666667
2    60000.000000
3    45000.000000
4    51666.666667
5    51666.666667
Name: Annual_Income, dtype: float64

In [35]:
# Fix Gender (Categorical → Mode)

df["Gender"].fillna(df["Gender"].mode()[0])

0      Male
1    Female
2      male
3    FEMALE
4      Male
5      Male
Name: Gender, dtype: object

In [ ]:
# ---------------------------------------
#     3. Remove Duplicates
# ---------------------------------------

In [ ]:
#Check duplicates
df.duplicated().sum()

np.int64(0)

In [41]:
df.duplicated(subset=["Customer_ID"]).sum()

np.int64(1)

In [44]:
#removing duplicate 
df.drop_duplicates(subset=["Customer_ID"], inplace=True)

In [45]:
df

  Customer_ID Signup_Date  Gender   Age  Annual_Income     City
0          C1  2022-01-01    Male  25.0   50000.000000   Mumbai
1          C2  2022-02-15  Female  30.0   51666.666667    Delhi
2          C3  2022-03-10    male  31.2   60000.000000  Chennai
3          C4  2022-01-01  FEMALE  45.0   45000.000000   Mumbai
4          C5  2022-05-20    Male  28.0   51666.666667    Delhi

In [ ]:
# -------------------------------------------
#     Step 4: Fix Data Types
# -------------------------------------------

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5 non-null      object
 1   Signup_Date    5 non-null      object
 2   Gender         5 non-null      object
 3   Age            5 non-null      float64
 4   Annual_Income  5 non-null      float64
 5   City           5 non-null      object
dtypes: float64(2), object(4)
memory usage: 280.0+ bytes

In [50]:
# signup_date → object
# Convert to datetime

df["Signup_Date"]= pd.to_datetime(df["Signup_Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    5 non-null      object
 1   Signup_Date    5 non-null      datetime64[ns]
 2   Gender         5 non-null      object
 3   Age            5 non-null      float64
 4   Annual_Income  5 non-null      float64
 5   City           5 non-null      object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 280.0+ bytes

In [55]:
# Age -> 31.2
#converting into proper age

# Method 1: Round → Convert to Int
df["Age"] = df["Age"].round().astype(int)
df

  Customer_ID Signup_Date  Gender  Age  Annual_Income     City
0          C1  2022-01-01    Male   25   50000.000000   Mumbai
1          C2  2022-02-15  Female   30   51666.666667    Delhi
2          C3  2022-03-10    male   31   60000.000000  Chennai
3          C4  2022-01-01  FEMALE   45   45000.000000   Mumbai
4          C5  2022-05-20    Male   28   51666.666667    Delhi

In [ ]:
# Method 2: Floor (Always Down)
df["Age"] = df["Age"].astype(int)

In [ ]:
# Method 3: Use np.ceil() (Always Up)
import numpy as np

df["Age"] = np.ceil(df["Age"]).astype(int)

In [65]:
df["annual_income"] =df["annual_income"].round()
df

  customer_id signup_date  gender  age  annual_income     city
0          C1  2022-01-01    Male   25        50000.0   Mumbai
1          C2  2022-02-15  Female   30        51667.0    Delhi
2          C3  2022-03-10    Male   31        60000.0  Chennai
3          C4  2022-01-01  Female   45        45000.0   Mumbai
4          C5  2022-05-20    Male   28        51667.0    Delhi

In [ ]:
#---------------------------------------
# 5. Clean Text Data (VERY IMPORTANT)
#---------------------------------------

In [ ]:
# Problem in Gender:
# Male
# male
# FEMALE
# Male (with space)

In [59]:
df["Gender"] = df["Gender"].str.lower().str.strip().str.capitalize()
df

  Customer_ID Signup_Date  Gender  Age  Annual_Income     City
0          C1  2022-01-01    Male   25   50000.000000   Mumbai
1          C2  2022-02-15  Female   30   51666.666667    Delhi
2          C3  2022-03-10    Male   31   60000.000000  Chennai
3          C4  2022-01-01  Female   45   45000.000000   Mumbai
4          C5  2022-05-20    Male   28   51666.666667    Delhi

In [ ]:
# ---------------------------------
# 6. Standardize Column Names
# ---------------------------------

In [66]:
# Customer_ID → customer_id
df.columns = df.columns.str.capitalize().str.strip()
df

  Customer_id Signup_date  Gender  Age  Annual_income     City
0          C1  2022-01-01    Male   25        50000.0   Mumbai
1          C2  2022-02-15  Female   30        51667.0    Delhi
2          C3  2022-03-10    Male   31        60000.0  Chennai
3          C4  2022-01-01  Female   45        45000.0   Mumbai
4          C5  2022-05-20    Male   28        51667.0    Delhi

In [ ]:
#-------------------------------------
# 7.Handling blank cells
#-------------------------------------

In [ ]:
# Step 1: Identify Blank Values

df.isnull().sum()
# This DOES NOT detect:" "

Customer_id      0
Signup_date      0
Gender           0
Age              0
Annual_income    0
City             0
dtype: int64

In [68]:
# Detect empty strings
(df == "").sum()

Customer_id      0
Signup_date      0
Gender           0
Age              0
Annual_income    0
City             0
dtype: int64

In [ ]:
# Step 2: Convert ALL blanks

# import numpy as np
# df = df.replace(["", " "], np.nan)

In [ ]:
# Step 3: Handle Missing Values
# df["Age"] = df["Age"].fillna(df["Age"].mean())
# df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [ ]:
# Drop rows
df.dropna(inplace=True)

In [ ]:
# Drop specific column nulls
df.dropna(subset=["Age"], inplace=True)

In [ ]:
# ---------------------------------------------
#         7. Validate Data (FINAL STEP)
# ---------------------------------------------

In [69]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_id    5 non-null      object
 1   Signup_date    5 non-null      datetime64[ns]
 2   Gender         5 non-null      object
 3   Age            5 non-null      int64
 4   Annual_income  5 non-null      float64
 5   City           5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 452.0+ bytes

Customer_id      0
Signup_date      0
Gender           0
Age              0
Annual_income    0
City             0
dtype: int64

In [71]:
print("Data after cleaning:")
df

Data after cleaning:

  Customer_id Signup_date  Gender  Age  Annual_income     City
0          C1  2022-01-01    Male   25        50000.0   Mumbai
1          C2  2022-02-15  Female   30        51667.0    Delhi
2          C3  2022-03-10    Male   31        60000.0  Chennai
3          C4  2022-01-01  Female   45        45000.0   Mumbai
4          C5  2022-05-20    Male   28        51667.0    Delhi