In [ ]:
# ===============================================
#                  Group By
# ===============================================

In [2]:
import pandas as pd

data = {
    "Product": ["A", "B", "A", "B", "C", "A", "C"],
    "Category": ["Electronics", "Clothing", "Electronics", "Clothing", "Electronics", "Clothing", "Electronics"],
    "Sales": [100, 200, 150, 300, 250, 120, 180],
    "Quantity": [1, 3, 2, 4, 2, 1, 3]
}

df = pd.DataFrame(data)
df

  Product     Category  Sales  Quantity
0       A  Electronics    100         1
1       B     Clothing    200         3
2       A  Electronics    150         2
3       B     Clothing    300         4
4       C  Electronics    250         2
5       A     Clothing    120         1
6       C  Electronics    180         3

In [28]:
# 1. Basic GroupBy
# Total Sales per Category

df.groupby("Category")["Sales"].agg(["sum"])

             sum
Category
Clothing     620
Electronics  680

In [ ]:
# 2. Multiple Aggregations

df.groupby("Category")["Sales"].agg(["sum", "mean", "max"])

             sum        mean  max
Category
Clothing     620  206.666667  300
Electronics  680  170.000000  250

In [34]:
# 3. GroupBy Multiple Columns

df.groupby(["Category", "Product"])["Sales"].agg(["sum"])

                     sum
Category    Product
Clothing    A        120
            B        500
Electronics A        250
            C        430

In [35]:
# 4. Count Values

df.groupby("Category")["Product"].count()

Category
Clothing       3
Electronics    4
Name: Product, dtype: int64

In [37]:
# 5. Reset Index (Important)
#  By default, groupby makes index

df.groupby("Category")["Sales"].sum().reset_index()

      Category  Sales
0     Clothing    620
1  Electronics    680

In [45]:
# 6. Rename Columns

df.groupby("Category")["Sales"].sum().reset_index().rename(columns={"Sales": "Total_Sales"})

      Category  Total_Sales
0     Clothing          620
1  Electronics          680

In [41]:
# 7. Sort Results

df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Electronics    680
Clothing       620
Name: Sales, dtype: int64

In [42]:
# 8. GroupBy with Multiple Columns + Multiple Aggregations

df.groupby(["Category", "Product"]).agg({
    "Sales": "sum",
    "Quantity": "mean"
}).reset_index()

      Category Product  Sales  Quantity
0     Clothing       A    120       1.0
1     Clothing       B    500       3.5
2  Electronics       A    250       1.5
3  Electronics       C    430       2.5

In [43]:
# 9. Apply Custom Function

df.groupby("Category")["Sales"].apply(lambda x: x.max() - x.min())

Category
Clothing       180
Electronics    150
Name: Sales, dtype: int64