In [2]:
# *******************************************
#           MERGING AND JOINING
# *******************************************

In [3]:
#  Sample Datasets

In [4]:
import pandas as pd

customers = pd.DataFrame({
    "Customer_ID": ["C1", "C2", "C3", "C4"],
    "Name": ["Amit", "Rahul", "Sneha", "Priya"]
})

orders = pd.DataFrame({
    "Customer_ID": ["C1", "C2", "C1", "C5"],
    "Amount": [1000, 2000, 1500, 3000]
})

In [5]:
customers

  Customer_ID   Name
0          C1   Amit
1          C2  Rahul
2          C3  Sneha
3          C4  Priya

In [6]:
orders

  Customer_ID  Amount
0          C1    1000
1          C2    2000
2          C1    1500
3          C5    3000

In [7]:
# join syntax:

# pd.merge(df1, df2, on="column", how="type")

In [8]:
# 1. INNER JOIN
# Only matching values

pd.merge(customers, orders, on="Customer_ID", how="inner")

  Customer_ID   Name  Amount
0          C1   Amit    1000
1          C1   Amit    1500
2          C2  Rahul    2000

In [9]:
# 2. LEFT JOIN
#All data from left table (customers)

pd.merge(customers, orders, on="Customer_ID", how="left")

  Customer_ID   Name  Amount
0          C1   Amit  1000.0
1          C1   Amit  1500.0
2          C2  Rahul  2000.0
3          C3  Sneha     NaN
4          C4  Priya     NaN

In [10]:
# 3. RIGHT JOIN
# All data from right table (orders)

pd.merge(customers, orders, on="Customer_ID", how="right")

  Customer_ID   Name  Amount
0          C1   Amit    1000
1          C2  Rahul    2000
2          C1   Amit    1500
3          C5    NaN    3000

In [11]:
# 4. OUTER JOIN
# Everything from both tables

pd.merge(customers, orders, on="Customer_ID", how="outer")

  Customer_ID   Name  Amount
0          C1   Amit  1000.0
1          C1   Amit  1500.0
2          C2  Rahul  2000.0
3          C3  Sneha     NaN
4          C4  Priya     NaN
5          C5    NaN  3000.0

In [12]:
# Exclusive joins

In [13]:
customers1 = pd.DataFrame({
    "Customer_ID": ["C1", "C2", "C3", "C4"]
})

orders1 = pd.DataFrame({
    "Customer_ID": ["C1", "C2", "C5"]
})

In [14]:
# Step: Use indicator=True

In [15]:
merged = pd.merge(customers, orders, on="Customer_ID", how="outer", indicator=True)

In [16]:
# 1. LEFT EXCLUSIVE JOIN
# Rows only in left table

In [17]:
merged[merged["_merge"] == "left_only"]

  Customer_ID   Name  Amount     _merge
3          C3  Sneha     NaN  left_only
4          C4  Priya     NaN  left_only

In [18]:
# 2. RIGHT EXCLUSIVE JOIN
# Rows only in right table

In [19]:
merged[merged["_merge"] == "right_only"]

  Customer_ID Name  Amount      _merge
5          C5  NaN  3000.0  right_only

In [20]:
# 3. FULL EXCLUSIVE JOIN
# Rows NOT matching in both tables

In [21]:
merged[merged["_merge"] != "both"]

  Customer_ID   Name  Amount      _merge
3          C3  Sneha     NaN   left_only
4          C4  Priya     NaN   left_only
5          C5    NaN  3000.0  right_only

In [22]:
# One-Line Versions

In [23]:
# Left Exclusive

pd.merge(customers, orders, on="Customer_ID", how="left", indicator=True)\
  .query('_merge == "left_only"')

  Customer_ID   Name  Amount     _merge
3          C3  Sneha     NaN  left_only
4          C4  Priya     NaN  left_only

In [24]:
# Right Exclusive

pd.merge(customers, orders, on="Customer_ID", how="right", indicator=True)\
  .query('_merge == "right_only"')

  Customer_ID Name  Amount      _merge
3          C5  NaN    3000  right_only

In [25]:
# Full Exclusive

pd.merge(customers, orders, on="Customer_ID", how="outer", indicator=True)\
  .query('_merge != "both"')

  Customer_ID   Name  Amount      _merge
3          C3  Sneha     NaN   left_only
4          C4  Priya     NaN   left_only
5          C5    NaN  3000.0  right_only

In [26]:
# only specific columns

In [27]:
# Method 1: Select Columns AFTER Merge (Most Common)

In [31]:
merged = pd.merge(customers, orders, on="Customer_ID", how="inner")

result = merged[["Customer_ID", "Name", "Amount"]]

result

  Customer_ID   Name  Amount
0          C1   Amit    1000
1          C1   Amit    1500
2          C2  Rahul    2000

In [ ]:
# Method 2: Select Columns BEFORE Merge

In [32]:
result2 = pd.merge(
    customers[["Customer_ID", "Name"]],
    orders[["Customer_ID", "Amount"]],
    on="Customer_ID",
    how="inner"
)

result2

  Customer_ID   Name  Amount
0          C1   Amit    1000
1          C1   Amit    1500
2          C2  Rahul    2000

In [ ]:
# Method 3: Using .loc

In [ ]:
merged.loc[:, ["Customer_ID", "Name", "Amount"]]

  Customer_ID   Name  Amount
0          C1   Amit    1000
1          C1   Amit    1500
2          C2  Rahul    2000

In [ ]:
# Method 4: Rename + Select Together

In [39]:
result4 = (
    pd.merge(customers, orders, on="Customer_ID")
    [["Customer_ID", "Name", "Amount"]]
    .rename(columns={"Amount": "Total_Amount"})
)
result4

  Customer_ID   Name  Total_Amount
0          C1   Amit          1000
1          C1   Amit          1500
2          C2  Rahul          2000

In [ ]:
# When both tables have same column names:

In [ ]:
# pd.merge(df1, df2, on="id", suffixes=("_cust", "_order"))
# result = merged[["id", "name_cust", "amount_order"]]