In [ ]:
# *******************************************************************
#                     Pivot Tables in Python
# *******************************************************************

In [ ]:
# What is Pivot Table?

# A pivot table is used to summarize data

# It helps you see patterns like:

# Avg salary per department
# Total sales per city
# Count of orders per product

In [ ]:
# Pivot = Group + Aggregate + Reshape

In [1]:
import pandas as pd

data = {
    "Department": ["HR","IT","IT","HR","Finance","Finance","IT"],
    "City": ["Delhi","Mumbai","Delhi","Delhi","Chennai","Chennai","Mumbai"],
    "Salary": [50000,60000,55000,52000,80000,75000,61000]
}

df = pd.DataFrame(data)

In [ ]:
# -----------------------------------------
#         1.Basic Pivot Table
# -----------------------------------------

In [2]:
pd.pivot_table(df, values="Salary", index="Department", aggfunc="mean")

                  Salary
Department
Finance     77500.000000
HR          51000.000000
IT          58666.666667

In [ ]:
# -----------------------------------------
#       2.Pivot with Multiple Columns
# -----------------------------------------

In [3]:
pd.pivot_table(df, values="Salary", index="Department", columns="City", aggfunc="mean")

City        Chennai    Delhi   Mumbai
Department
Finance     77500.0      NaN      NaN
HR              NaN  51000.0      NaN
IT              NaN  55000.0  60500.0

In [ ]:
# -----------------------------------------
#      3.Multiple Aggregations
# -----------------------------------------

In [8]:
pd.pivot_table(df, values="Salary", index="Department", aggfunc=["mean","max","min"])

                    mean    max    min
                  Salary Salary Salary
Department
Finance     77500.000000  80000  75000
HR          51000.000000  52000  50000
IT          58666.666667  61000  55000

In [11]:
pd.pivot_table(df,values="Salary", index="Department", aggfunc={"Salary": [("average_sal", "mean"),("high", "max"),("lowest", "min")]})

             average_sal   high  lowest
Department
Finance     77500.000000  80000   75000
HR          51000.000000  52000   50000
IT          58666.666667  61000   55000

In [18]:
pivot = pd.pivot_table(df, values="Salary", index="Department", aggfunc=["mean","max","min"])
pivot.columns = ["average_sal", "high", "lowest"]
pivot

             average_sal   high  lowest
Department
Finance     77500.000000  80000   75000
HR          51000.000000  52000   50000
IT          58666.666667  61000   55000

In [19]:
# -----------------------------------------
#     4.Count Values
# -----------------------------------------

In [23]:
pd.pivot_table(df, values="Salary", index="Department", aggfunc="count")

            Salary
Department
Finance          2
HR               2
IT               3

In [ ]:
# -----------------------------------------
#     5.Fill Missing Values
# -----------------------------------------

In [24]:
pd.pivot_table(df, values="Salary", index="Department", columns="City", aggfunc="mean", fill_value=0)

City        Chennai    Delhi   Mumbai
Department
Finance     77500.0      0.0      0.0
HR              0.0  51000.0      0.0
IT              0.0  55000.0  60500.0