In [1]:
# *******************************************
#         Selecting & Filtering
# *******************************************

In [ ]:
# Selecting rows
# .loc[] (label-based)
# .iloc[] (index-based)
# Filtering (like SQL WHERE)Multiple conditions

In [3]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch"],
    "Price": [60000, 20000, 30000, 2000, 5000],
    "Quantity": [5, 10, 7, 20, 15]
}

df = pd.DataFrame(data)

In [ ]:
# 1. Select Rows

In [4]:
# First row
df.iloc[0]

Product     Laptop
Price        60000
Quantity         5
Name: 0, dtype: object

In [5]:
# Multiple rows
df.iloc[0:3]

  Product  Price  Quantity
0  Laptop  60000         5
1  Mobile  20000        10
2  Tablet  30000         7

In [6]:
# 2. .iloc[] (Index Based)

In [8]:
# Uses row index numbers
df.iloc[1, 2]
# Row 1, Column 2

np.int64(10)

In [9]:
# Select rows & columns
df.iloc[0:3, 0:2]

  Product  Price
0  Laptop  60000
1  Mobile  20000
2  Tablet  30000

In [ ]:
# 3. .loc[] (Label Based)

In [10]:
# Uses column names
df.loc[0, "Price"]

np.int64(60000)

In [11]:
# Select multiple
df.loc[0:2, ["Product", "Price"]]

  Product  Price
0  Laptop  60000
1  Mobile  20000
2  Tablet  30000

In [ ]:
# 4. Filtering

In [12]:
# Products with Price > 10000
df[df["Price"] > 10000]

  Product  Price  Quantity
0  Laptop  60000         5
1  Mobile  20000        10
2  Tablet  30000         7

In [ ]:
# 5. Multiple Conditions

In [ ]:
# AND condition
df[(df["Price"] > 10000) & (df["Quantity"] > 5)]

  Product  Price  Quantity
1  Mobile  20000        10
2  Tablet  30000         7

In [14]:
# OR condition
df[(df["Price"] < 5000) | (df["Quantity"] > 10)]

      Product  Price  Quantity
3  Headphones   2000        20
4  Smartwatch   5000        15

In [ ]:
# 6. Select Specific Columns After Filter

In [15]:
df[df["Price"] > 10000][["Product", "Price"]]

  Product  Price
0  Laptop  60000
1  Mobile  20000
2  Tablet  30000