In [34]:
# **********************************
#         PRACTICE
# **********************************

In [35]:
# ----------------------------------------
#     Dataset 1 — E-commerce Products
# ----------------------------------------

In [36]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch", "Monitor"],
    "Price": [60000, 20000, 30000, 2000, 5000, 15000],
    "Quantity": [5, 10, 7, 20, 15, 8]
}

df = pd.DataFrame(data)

In [37]:
# Task 1 — Basic Selection
# Select first 3 rows using .iloc[]

In [38]:
df.iloc[0:4]

      Product  Price  Quantity
0      Laptop  60000         5
1      Mobile  20000        10
2      Tablet  30000         7
3  Headphones   2000        20

In [39]:
# Task 2 — Column Selection
# Select only Product and Price using .loc[]

In [40]:
df.loc[:, ["Product", "Price"]]

      Product  Price
0      Laptop  60000
1      Mobile  20000
2      Tablet  30000
3  Headphones   2000
4  Smartwatch   5000
5     Monitor  15000

In [41]:
# Task 3 — Simple Filter
# Products where Price > 20000

In [42]:
df[df["Price"]>20000]

  Product  Price  Quantity
0  Laptop  60000         5
2  Tablet  30000         7

In [43]:
# Task 4 — Quantity Filter
# Products where Quantity >= 10

In [44]:
df[df["Quantity"]>=10]

      Product  Price  Quantity
1      Mobile  20000        10
3  Headphones   2000        20
4  Smartwatch   5000        15

In [45]:
# Task 5 — Multiple Condition (AND)
# Price > 10000 AND Quantity > 5

In [46]:
df[(df["Price"]>10000) & (df["Quantity"]>5)]

   Product  Price  Quantity
1   Mobile  20000        10
2   Tablet  30000         7
5  Monitor  15000         8

In [47]:
# Task 6 — Multiple Condition (OR)
# Price < 5000 OR Quantity > 10

In [48]:
df[(df["Price"]<5000) | (df["Quantity"]>10)]

      Product  Price  Quantity
3  Headphones   2000        20
4  Smartwatch   5000        15

In [49]:
# Task 7 — Column + Filter
# Show only Product and Quantity
# Where Price > 10000

In [50]:
df[df["Price"]>10000][["Product", "Quantity"]]

   Product  Quantity
0   Laptop         5
1   Mobile        10
2   Tablet         7
5  Monitor         8

In [51]:
# Task 8 — Update with Condition
# Increase Price by 10%
# Only where Quantity > 10

In [55]:
df.loc[df["Quantity"] > 10, "Price"] *= 1.10
print(df)

      Product    Price  Quantity
0      Laptop  60000.0         5
1      Mobile  20000.0        10
2      Tablet  30000.0         7
3  Headphones   2662.0        20
4  Smartwatch   6655.0        15
5     Monitor  15000.0         8

In [ ]:
# ------------------------------------------
#         Dataset 2 — Employee Data
# ------------------------------------------

In [56]:
data = {
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Salary": [25000, 50000, 70000, 30000, 90000, 45000],
    "Experience": [1, 4, 6, 2, 8, 3],
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT"]
}

emp = pd.DataFrame(data)

In [ ]:
# Task 1 — High Salary
# Employees with Salary > 50000

In [57]:
emp[emp["Salary"]>5000]

  Name  Salary  Experience Department
0    A   25000           1         HR
1    B   50000           4         IT
2    C   70000           6         IT
3    D   30000           2         HR
4    E   90000           8    Finance
5    F   45000           3         IT

In [ ]:
# Task 2 — Department Filter
# Employees in "IT" department

In [58]:
emp[emp["Department"].str.contains("IT")]

  Name  Salary  Experience Department
1    B   50000           4         IT
2    C   70000           6         IT
5    F   45000           3         IT

In [ ]:
# Task 3 — Multiple Condition
# Salary > 40000 AND Experience > 3

In [59]:
emp[(emp["Salary"]>40000) & (emp["Experience"]>3)]

  Name  Salary  Experience Department
1    B   50000           4         IT
2    C   70000           6         IT
4    E   90000           8    Finance

In [ ]:
# Task 4 — OR Condition
# Department = HR OR Salary > 60000

In [61]:
emp[(emp["Department"].str.contains("HR")) | (emp["Salary"]>60000)]

  Name  Salary  Experience Department
0    A   25000           1         HR
2    C   70000           6         IT
3    D   30000           2         HR
4    E   90000           8    Finance

In [ ]:
# # Task 5 — LIKE Operator
# Names containing "A"

In [62]:
emp[emp["Name"].str.contains("A")]

  Name  Salary  Experience Department
0    A   25000           1         HR

In [ ]:
# Task 6 — Column + Filter
# Show only Name and Salary
# Where Experience >= 3

In [65]:
emp[emp["Experience"]>3][["Name", "Salary"]]

  Name  Salary
1    B   50000
2    C   70000
4    E   90000

In [ ]:
# Task 7 — Update Data 
# Increase salary by 5000
# Only for IT employees

In [67]:
emp.loc[emp["Department"] == "IT", "Salary"] += 5000

print(emp)

  Name  Salary  Experience Department
0    A   25000           1         HR
1    B   55000           4         IT
2    C   75000           6         IT
3    D   30000           2         HR
4    E   90000           8    Finance
5    F   50000           3         IT

In [ ]:
# Task 8 — Advanced Filter 
# Employees:
# Experience between 3 and 6

np.int64(5)

In [71]:
emp[(emp["Experience"]>=3) & (emp["Experience"]<=6)]

  Name  Salary  Experience Department
1    B   55000           4         IT
2    C   75000           6         IT
5    F   50000           3         IT

In [ ]:
# ---------------------------------------
#     Dataset 3 — Student Data
# ---------------------------------------

In [72]:
data = {
    "Name": ["John", "Sam", "Anna", "Mike", "Sara"],
    "Math": [78, 40, 88, 60, 30],
    "Science": [85, 35, 92, 65, 25],
    "English": [90, 50, 95, 70, 40]
}

students = pd.DataFrame(data)

In [ ]:
# Task 1 — Failed Students
# Students where any subject < 35

In [86]:
failed_students = students[
    (students[["Math", "Science", "English"]] < 35).any(axis=1)
]

failed_students

   Name  Math  Science  English
4  Sara    30       25       40

In [ ]:
# Task 2 — Top Students
# Students where all subjects > 80

In [89]:
Top_students = students[
    (students[["Math", "Science", "English"]]>80).all(axis=1)
]
Top_students

   Name  Math  Science  English
2  Anna    88       92       95

In [ ]:
# Task 3 — Average Filter
# Students with average > 70

In [103]:
avg = students[["Math", "Science", "English"]].mean(axis=1)
result = students[avg > 70]
result

   Name  Math  Science  English
0  John    78       85       90
2  Anna    88       92       95

In [104]:
# Task 4 — Column Selection + Filter
# Show Name and Math
# Where Science > 60

In [106]:
students[students["Science"]>60] [["Name", "Math"]]

   Name  Math
0  John    78
2  Anna    88
3  Mike    60

In [ ]:
# Task 5 — Update Marks 🔥
# Add 5 marks
# Only where average < 50

In [ ]:

avg = students[["Math", "Science", "English"]].mean(axis=1)
condition = avg < 50
students.loc[condition, ["Math", "Science", "English"]] += 5
print(students)

   Name  Math  Science  English
0  John    78       85       90
1   Sam    45       40       55
2  Anna    88       92       95
3  Mike    60       65       70
4  Sara    35       30       45

In [ ]:
# task6
# show all the data

In [74]:
students.iloc[0:,]

   Name  Math  Science  English
0  John    78       85       90
1   Sam    40       35       50
2  Anna    88       92       95
3  Mike    60       65       70
4  Sara    30       25       40

In [ ]:
#task7
# show only first 3 columns

In [79]:
students.head()

   Name  Math  Science  English
0  John    78       85       90
1   Sam    40       35       50
2  Anna    88       92       95
3  Mike    60       65       70
4  Sara    30       25       40